# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab7fb0722e2db2b42c95ca29169d796d2d39cbf58514cada96853c3cfeee6fb6459da1a8c36b4a1e6084912479e5dfc5a14e56bcb2cee48f6e4cf56877cfd987

test:
  secret_key_base: 1e345cc3a4bd9011c762194284058790b15a89116fc619eab13efc350843c6a536957e44f44d7c638ea20cb7ff3ce9c389ce58f388b1c76e61b932f93e1bc524

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
